/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.swigbls;

public class PrivateKeyVector extends java.util.AbstractList<PrivateKey> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PrivateKeyVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrivateKeyVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_PrivateKeyVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  PrivateKeyVector(java.util.Collection<PrivateKey> e) {
    this.reserve(e.size());
    for(PrivateKey value: e) {
      this.push_back(value);
    }
  }

  public PrivateKeyVector() {
    this(blssignaturesJNI.new_PrivateKeyVector__SWIG_0(), true);
  }

  public PrivateKeyVector(long n) {
    this(blssignaturesJNI.new_PrivateKeyVector__SWIG_1(n), true);
  }

  public PrivateKeyVector(PrivateKeyVector o) {
    this(blssignaturesJNI.new_PrivateKeyVector__SWIG_2(PrivateKeyVector.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.PrivateKeyVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.PrivateKeyVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.PrivateKeyVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    blssignaturesJNI.PrivateKeyVector_clear(swigCPtr, this);
  }

  public void push_back(PrivateKey x) {
    blssignaturesJNI.PrivateKeyVector_push_back(swigCPtr, this, PrivateKey.getCPtr(x), x);
  }

  public PrivateKey get(int i) {
    return new PrivateKey(blssignaturesJNI.PrivateKeyVector_get(swigCPtr, this, i), false);
  }

  public PrivateKey set(int i, PrivateKey VECTOR_VALUE_IN) {
    return new PrivateKey(blssignaturesJNI.PrivateKeyVector_set(swigCPtr, this, i, PrivateKey.getCPtr(VECTOR_VALUE_IN), VECTOR_VALUE_IN), true);
  }

  public int size() {
    return blssignaturesJNI.PrivateKeyVector_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.PrivateKeyVector_removeRange(swigCPtr, this, from, to);
  }

}
