/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.swigbls;

public class PublicKeyVector extends java.util.AbstractList<PublicKey> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PublicKeyVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublicKeyVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_PublicKeyVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  PublicKeyVector(java.util.Collection<PublicKey> e) {
    this.reserve(e.size());
    for(PublicKey value: e) {
      this.push_back(value);
    }
  }

  public PublicKeyVector() {
    this(blssignaturesJNI.new_PublicKeyVector__SWIG_0(), true);
  }

  public PublicKeyVector(long n) {
    this(blssignaturesJNI.new_PublicKeyVector__SWIG_1(n), true);
  }

  public PublicKeyVector(PublicKeyVector o) {
    this(blssignaturesJNI.new_PublicKeyVector__SWIG_2(PublicKeyVector.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.PublicKeyVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.PublicKeyVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.PublicKeyVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    blssignaturesJNI.PublicKeyVector_clear(swigCPtr, this);
  }

  public void push_back(PublicKey x) {
    blssignaturesJNI.PublicKeyVector_push_back(swigCPtr, this, PublicKey.getCPtr(x), x);
  }

  public PublicKey get(int i) {
    return new PublicKey(blssignaturesJNI.PublicKeyVector_get(swigCPtr, this, i), false);
  }

  public PublicKey set(int i, PublicKey VECTOR_VALUE_IN) {
    return new PublicKey(blssignaturesJNI.PublicKeyVector_set(swigCPtr, this, i, PublicKey.getCPtr(VECTOR_VALUE_IN), VECTOR_VALUE_IN), true);
  }

  public int size() {
    return blssignaturesJNI.PublicKeyVector_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.PublicKeyVector_removeRange(swigCPtr, this, from, to);
  }

}
