/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.swigbls;

public class Signature {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Signature(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Signature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_Signature(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Signature FromBytes(byte[] data) {
    return new Signature(blssignaturesJNI.Signature_FromBytes__SWIG_0(data), true);
  }

  public static Signature FromBytes(byte[] data, SWIGTYPE_p_AggregationInfo info) {
    return new Signature(blssignaturesJNI.Signature_FromBytes__SWIG_1(data, SWIGTYPE_p_AggregationInfo.getCPtr(info)), true);
  }

  public static Signature FromG2(SWIGTYPE_p_g2_t element) {
    return new Signature(blssignaturesJNI.Signature_FromG2__SWIG_0(SWIGTYPE_p_g2_t.getCPtr(element)), true);
  }

  public static Signature FromG2(SWIGTYPE_p_g2_t element, SWIGTYPE_p_AggregationInfo info) {
    return new Signature(blssignaturesJNI.Signature_FromG2__SWIG_1(SWIGTYPE_p_g2_t.getCPtr(element), SWIGTYPE_p_AggregationInfo.getCPtr(info)), true);
  }

  public static Signature FromInsecureSig(InsecureSignature sig) {
    return new Signature(blssignaturesJNI.Signature_FromInsecureSig__SWIG_0(InsecureSignature.getCPtr(sig), sig), true);
  }

  public static Signature FromInsecureSig(InsecureSignature sig, SWIGTYPE_p_AggregationInfo info) {
    return new Signature(blssignaturesJNI.Signature_FromInsecureSig__SWIG_1(InsecureSignature.getCPtr(sig), sig, SWIGTYPE_p_AggregationInfo.getCPtr(info)), true);
  }

  public Signature(Signature signature) {
    this(blssignaturesJNI.new_Signature(Signature.getCPtr(signature), signature), true);
  }

  public boolean Verify() {
    return blssignaturesJNI.Signature_Verify(swigCPtr, this);
  }

  public static Signature AggregateSigs(SignatureVector sigs) {
    return new Signature(blssignaturesJNI.Signature_AggregateSigs(SignatureVector.getCPtr(sigs), sigs), true);
  }

  public Signature DivideBy(SignatureVector divisorSigs) {
    return new Signature(blssignaturesJNI.Signature_DivideBy(swigCPtr, this, SignatureVector.getCPtr(divisorSigs), divisorSigs), true);
  }

  public SWIGTYPE_p_AggregationInfo GetAggregationInfo() {
    long cPtr = blssignaturesJNI.Signature_GetAggregationInfo(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_AggregationInfo(cPtr, false);
  }

  public void SetAggregationInfo(SWIGTYPE_p_AggregationInfo newAggregationInfo) {
    blssignaturesJNI.Signature_SetAggregationInfo(swigCPtr, this, SWIGTYPE_p_AggregationInfo.getCPtr(newAggregationInfo));
  }

  public void Serialize(byte[] buffer) {
    blssignaturesJNI.Signature_Serialize__SWIG_0(swigCPtr, this, buffer);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(blssignaturesJNI.Signature_Serialize__SWIG_1(swigCPtr, this), true);
  }

  public final static long SIGNATURE_SIZE = blssignaturesJNI.Signature_SIGNATURE_SIZE_get();
}
