/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashcore.blssignatures;

public interface blssignaturesConstants {
  public final static int BLS_CURVE_ID_SIZE = blssignaturesJNI.BLS_CURVE_ID_SIZE_get();
  public final static int BLS_CURVE_SECKEY_SIZE = blssignaturesJNI.BLS_CURVE_SECKEY_SIZE_get();
  public final static int BLS_CURVE_PUBKEY_SIZE = blssignaturesJNI.BLS_CURVE_PUBKEY_SIZE_get();
  public final static int BLS_CURVE_SIG_SIZE = blssignaturesJNI.BLS_CURVE_SIG_SIZE_get();
}
