/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashcore.blssignatures;

public class CBLSSecretKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CBLSSecretKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CBLSSecretKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_CBLSSecretKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void AggregateInsecure(CBLSSecretKey o) {
    blssignaturesJNI.CBLSSecretKey_AggregateInsecure__SWIG_0(swigCPtr, this, CBLSSecretKey.getCPtr(o), o);
  }

  public static CBLSSecretKey AggregateInsecure(SWIGTYPE_p_std__vectorT_CBLSSecretKey_t sks) {
    return new CBLSSecretKey(blssignaturesJNI.CBLSSecretKey_AggregateInsecure__SWIG_1(SWIGTYPE_p_std__vectorT_CBLSSecretKey_t.getCPtr(sks)), true);
  }

  public void MakeNewKey() {
    blssignaturesJNI.CBLSSecretKey_MakeNewKey(swigCPtr, this);
  }

  public boolean SecretKeyShare(SWIGTYPE_p_std__vectorT_CBLSSecretKey_t msk, CBLSId id) {
    return blssignaturesJNI.CBLSSecretKey_SecretKeyShare(swigCPtr, this, SWIGTYPE_p_std__vectorT_CBLSSecretKey_t.getCPtr(msk), CBLSId.getCPtr(id), id);
  }

  public CBLSPublicKey GetPublicKey() {
    return new CBLSPublicKey(blssignaturesJNI.CBLSSecretKey_GetPublicKey(swigCPtr, this), true);
  }

  public CBLSSignature Sign(SWIGTYPE_p_uint256 hash) {
    return new CBLSSignature(blssignaturesJNI.CBLSSecretKey_Sign(swigCPtr, this, SWIGTYPE_p_uint256.getCPtr(hash)), true);
  }

  public CBLSSecretKey() {
    this(blssignaturesJNI.new_CBLSSecretKey(), true);
  }

}
