/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashcore.blssignatures;

public class CBLSPublicKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CBLSPublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CBLSPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_CBLSPublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void AggregateInsecure(CBLSPublicKey o) {
    blssignaturesJNI.CBLSPublicKey_AggregateInsecure__SWIG_0(swigCPtr, this, CBLSPublicKey.getCPtr(o), o);
  }

  public static CBLSPublicKey AggregateInsecure(SWIGTYPE_p_std__vectorT_CBLSPublicKey_t pks) {
    return new CBLSPublicKey(blssignaturesJNI.CBLSPublicKey_AggregateInsecure__SWIG_1(SWIGTYPE_p_std__vectorT_CBLSPublicKey_t.getCPtr(pks)), true);
  }

  public boolean PublicKeyShare(SWIGTYPE_p_std__vectorT_CBLSPublicKey_t mpk, CBLSId id) {
    return blssignaturesJNI.CBLSPublicKey_PublicKeyShare(swigCPtr, this, SWIGTYPE_p_std__vectorT_CBLSPublicKey_t.getCPtr(mpk), CBLSId.getCPtr(id), id);
  }

  public boolean DHKeyExchange(CBLSSecretKey sk, CBLSPublicKey pk) {
    return blssignaturesJNI.CBLSPublicKey_DHKeyExchange(swigCPtr, this, CBLSSecretKey.getCPtr(sk), sk, CBLSPublicKey.getCPtr(pk), pk);
  }

  public CBLSPublicKey() {
    this(blssignaturesJNI.new_CBLSPublicKey(), true);
  }

}
