/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashcore.blssignatures;

public class CBLSPrivateKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CBLSPrivateKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CBLSPrivateKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_CBLSPrivateKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean IsValid() {
    return blssignaturesJNI.CBLSPrivateKey_IsValid(swigCPtr, this);
  }

  public void SetBuf(SWIGTYPE_p_void buf, long size) {
    blssignaturesJNI.CBLSPrivateKey_SetBuf(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), size);
  }

  public void Reset() {
    blssignaturesJNI.CBLSPrivateKey_Reset(swigCPtr, this);
  }

  public void GetBuf(SWIGTYPE_p_void buf, long size) {
    blssignaturesJNI.CBLSPrivateKey_GetBuf(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), size);
  }

  public SWIGTYPE_p_uint256 GetHash() {
    return new SWIGTYPE_p_uint256(blssignaturesJNI.CBLSPrivateKey_GetHash(swigCPtr, this), false);
  }

  public void UpdateHash() {
    blssignaturesJNI.CBLSPrivateKey_UpdateHash(swigCPtr, this);
  }

  public boolean SetHexStr(SWIGTYPE_p_std__string str) {
    return blssignaturesJNI.CBLSPrivateKey_SetHexStr(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(str));
  }

  public void CheckMalleable(SWIGTYPE_p_void buf, long size) {
    blssignaturesJNI.CBLSPrivateKey_CheckMalleable(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), size);
  }

  public SWIGTYPE_p_std__string ToString() {
    return new SWIGTYPE_p_std__string(blssignaturesJNI.CBLSPrivateKey_ToString(swigCPtr, this), true);
  }

  public final static long SerSize = blssignaturesJNI.CBLSPrivateKey_SerSize_get();
}
