/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashcore.blssignatures;

public class SWIGTYPE_p_std__vectorT_CBLSSignature_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_std__vectorT_CBLSSignature_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_std__vectorT_CBLSSignature_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_std__vectorT_CBLSSignature_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

