/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "bls-signatures/src/bls.hpp"
#include "bls-signatures/src/chaincode.hpp"
#include "bls-signatures/src/extendedprivatekey.hpp"
#include "bls-signatures/src/extendedpublickey.hpp"
#include "bls-signatures/src/privatekey.hpp"
#include "bls-signatures/src/publickey.hpp"
#include "bls-signatures/src/signature.hpp"
#include "bls-signatures/src/aggregationinfo.hpp"
#include "cpp/bls.h"


#include <vector>
#include <stdexcept>


#include <stdint.h>		// Use the C99 official header


#include <typeinfo>
#include <stdexcept>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_BLS_1CURVE_1ID_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(32);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_BLS_1CURVE_1SECKEY_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(32);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_BLS_1CURVE_1PUBKEY_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(48);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_BLS_1CURVE_1SIG_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(96);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSId_1SetInt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  CBLSId *arg1 = (CBLSId *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSId **)&jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->SetInt(arg2);
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSId_1SetHash(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  CBLSId *arg1 = (CBLSId *) 0 ;
  uint256 *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSId **)&jarg1; 
  arg2 = *(uint256 **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "uint256 const & reference is null");
    return ;
  } 
  (arg1)->SetHash((uint256 const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSId_1FromInt(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  int64_t arg1 ;
  CBLSId result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int64_t)jarg1; 
  result = CBLSId::FromInt(arg1);
  *(CBLSId **)&jresult = new CBLSId((const CBLSId &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSId_1FromHash(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  uint256 *arg1 = 0 ;
  CBLSId result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uint256 **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "uint256 const & reference is null");
    return 0;
  } 
  result = CBLSId::FromHash((uint256 const &)*arg1);
  *(CBLSId **)&jresult = new CBLSId((const CBLSId &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_new_1CBLSId(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CBLSId *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CBLSId *)new CBLSId();
  *(CBLSId **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_delete_1CBLSId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CBLSId *arg1 = (CBLSId *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CBLSId **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSecretKey_1AggregateInsecure_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  CBLSSecretKey *arg1 = (CBLSSecretKey *) 0 ;
  CBLSSecretKey *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(CBLSSecretKey **)&jarg1; 
  arg2 = *(CBLSSecretKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSSecretKey const & reference is null");
    return ;
  } 
  (arg1)->AggregateInsecure((CBLSSecretKey const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSecretKey_1AggregateInsecure_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< CBLSSecretKey > *arg1 = 0 ;
  CBLSSecretKey result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< CBLSSecretKey > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSSecretKey > const & reference is null");
    return 0;
  } 
  result = CBLSSecretKey::AggregateInsecure((std::vector< CBLSSecretKey > const &)*arg1);
  *(CBLSSecretKey **)&jresult = new CBLSSecretKey((const CBLSSecretKey &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSecretKey_1MakeNewKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  CBLSSecretKey *arg1 = (CBLSSecretKey *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSSecretKey **)&jarg1; 
  (arg1)->MakeNewKey();
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSecretKey_1SecretKeyShare(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jboolean jresult = 0 ;
  CBLSSecretKey *arg1 = (CBLSSecretKey *) 0 ;
  std::vector< CBLSSecretKey > *arg2 = 0 ;
  CBLSId *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(CBLSSecretKey **)&jarg1; 
  arg2 = *(std::vector< CBLSSecretKey > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSSecretKey > const & reference is null");
    return 0;
  } 
  arg3 = *(CBLSId **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSId const & reference is null");
    return 0;
  } 
  result = (bool)(arg1)->SecretKeyShare((std::vector< CBLSSecretKey > const &)*arg2,(CBLSId const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSecretKey_1GetPublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CBLSSecretKey *arg1 = (CBLSSecretKey *) 0 ;
  CBLSPublicKey result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSSecretKey **)&jarg1; 
  result = ((CBLSSecretKey const *)arg1)->GetPublicKey();
  *(CBLSPublicKey **)&jresult = new CBLSPublicKey((const CBLSPublicKey &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSecretKey_1Sign(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CBLSSecretKey *arg1 = (CBLSSecretKey *) 0 ;
  uint256 *arg2 = 0 ;
  CBLSSignature result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSSecretKey **)&jarg1; 
  arg2 = *(uint256 **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "uint256 const & reference is null");
    return 0;
  } 
  result = ((CBLSSecretKey const *)arg1)->Sign((uint256 const &)*arg2);
  *(CBLSSignature **)&jresult = new CBLSSignature((const CBLSSignature &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_new_1CBLSSecretKey(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CBLSSecretKey *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CBLSSecretKey *)new CBLSSecretKey();
  *(CBLSSecretKey **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_delete_1CBLSSecretKey(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CBLSSecretKey *arg1 = (CBLSSecretKey *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CBLSSecretKey **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPublicKey_1AggregateInsecure_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  CBLSPublicKey *arg1 = (CBLSPublicKey *) 0 ;
  CBLSPublicKey *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(CBLSPublicKey **)&jarg1; 
  arg2 = *(CBLSPublicKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSPublicKey const & reference is null");
    return ;
  } 
  (arg1)->AggregateInsecure((CBLSPublicKey const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPublicKey_1AggregateInsecure_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< CBLSPublicKey > *arg1 = 0 ;
  CBLSPublicKey result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< CBLSPublicKey > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSPublicKey > const & reference is null");
    return 0;
  } 
  result = CBLSPublicKey::AggregateInsecure((std::vector< CBLSPublicKey > const &)*arg1);
  *(CBLSPublicKey **)&jresult = new CBLSPublicKey((const CBLSPublicKey &)result); 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPublicKey_1PublicKeyShare(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jboolean jresult = 0 ;
  CBLSPublicKey *arg1 = (CBLSPublicKey *) 0 ;
  std::vector< CBLSPublicKey > *arg2 = 0 ;
  CBLSId *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(CBLSPublicKey **)&jarg1; 
  arg2 = *(std::vector< CBLSPublicKey > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSPublicKey > const & reference is null");
    return 0;
  } 
  arg3 = *(CBLSId **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSId const & reference is null");
    return 0;
  } 
  result = (bool)(arg1)->PublicKeyShare((std::vector< CBLSPublicKey > const &)*arg2,(CBLSId const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPublicKey_1DHKeyExchange(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jobject jarg3_) {
  jboolean jresult = 0 ;
  CBLSPublicKey *arg1 = (CBLSPublicKey *) 0 ;
  CBLSSecretKey *arg2 = 0 ;
  CBLSPublicKey *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg3_;
  arg1 = *(CBLSPublicKey **)&jarg1; 
  arg2 = *(CBLSSecretKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSSecretKey const & reference is null");
    return 0;
  } 
  arg3 = *(CBLSPublicKey **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSPublicKey const & reference is null");
    return 0;
  } 
  result = (bool)(arg1)->DHKeyExchange((CBLSSecretKey const &)*arg2,(CBLSPublicKey const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_new_1CBLSPublicKey(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CBLSPublicKey *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CBLSPublicKey *)new CBLSPublicKey();
  *(CBLSPublicKey **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_delete_1CBLSPublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CBLSPublicKey *arg1 = (CBLSPublicKey *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CBLSPublicKey **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_new_1CBLSSignature_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CBLSSignature *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CBLSSignature *)new CBLSSignature();
  *(CBLSSignature **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_new_1CBLSSignature_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CBLSSignature *arg1 = 0 ;
  CBLSSignature *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSSignature **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSSignature const & reference is null");
    return 0;
  } 
  result = (CBLSSignature *)new CBLSSignature((CBLSSignature const &)*arg1);
  *(CBLSSignature **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1AggregateInsecure_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  CBLSSignature *arg1 = (CBLSSignature *) 0 ;
  CBLSSignature *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(CBLSSignature **)&jarg1; 
  arg2 = *(CBLSSignature **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSSignature const & reference is null");
    return ;
  } 
  (arg1)->AggregateInsecure((CBLSSignature const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1AggregateInsecure_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< CBLSSignature > *arg1 = 0 ;
  CBLSSignature result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< CBLSSignature > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSSignature > const & reference is null");
    return 0;
  } 
  result = CBLSSignature::AggregateInsecure((std::vector< CBLSSignature > const &)*arg1);
  *(CBLSSignature **)&jresult = new CBLSSignature((const CBLSSignature &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1AggregateSecure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  std::vector< CBLSSignature > *arg1 = 0 ;
  std::vector< CBLSPublicKey > *arg2 = 0 ;
  uint256 *arg3 = 0 ;
  CBLSSignature result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< CBLSSignature > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSSignature > const & reference is null");
    return 0;
  } 
  arg2 = *(std::vector< CBLSPublicKey > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSPublicKey > const & reference is null");
    return 0;
  } 
  arg3 = *(uint256 **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "uint256 const & reference is null");
    return 0;
  } 
  result = CBLSSignature::AggregateSecure((std::vector< CBLSSignature > const &)*arg1,(std::vector< CBLSPublicKey > const &)*arg2,(uint256 const &)*arg3);
  *(CBLSSignature **)&jresult = new CBLSSignature((const CBLSSignature &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1SubInsecure(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  CBLSSignature *arg1 = (CBLSSignature *) 0 ;
  CBLSSignature *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(CBLSSignature **)&jarg1; 
  arg2 = *(CBLSSignature **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSSignature const & reference is null");
    return ;
  } 
  (arg1)->SubInsecure((CBLSSignature const &)*arg2);
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1VerifyInsecure(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3) {
  jboolean jresult = 0 ;
  CBLSSignature *arg1 = (CBLSSignature *) 0 ;
  CBLSPublicKey *arg2 = 0 ;
  uint256 *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(CBLSSignature **)&jarg1; 
  arg2 = *(CBLSPublicKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "CBLSPublicKey const & reference is null");
    return 0;
  } 
  arg3 = *(uint256 **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "uint256 const & reference is null");
    return 0;
  } 
  result = (bool)((CBLSSignature const *)arg1)->VerifyInsecure((CBLSPublicKey const &)*arg2,(uint256 const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1VerifyInsecureAggregated(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CBLSSignature *arg1 = (CBLSSignature *) 0 ;
  std::vector< CBLSPublicKey > *arg2 = 0 ;
  std::vector< uint256 > *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSSignature **)&jarg1; 
  arg2 = *(std::vector< CBLSPublicKey > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSPublicKey > const & reference is null");
    return 0;
  } 
  arg3 = *(std::vector< uint256 > **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< uint256 > const & reference is null");
    return 0;
  } 
  result = (bool)((CBLSSignature const *)arg1)->VerifyInsecureAggregated((std::vector< CBLSPublicKey > const &)*arg2,(std::vector< uint256 > const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1VerifySecureAggregated(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CBLSSignature *arg1 = (CBLSSignature *) 0 ;
  std::vector< CBLSPublicKey > *arg2 = 0 ;
  uint256 *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSSignature **)&jarg1; 
  arg2 = *(std::vector< CBLSPublicKey > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSPublicKey > const & reference is null");
    return 0;
  } 
  arg3 = *(uint256 **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "uint256 const & reference is null");
    return 0;
  } 
  result = (bool)((CBLSSignature const *)arg1)->VerifySecureAggregated((std::vector< CBLSPublicKey > const &)*arg2,(uint256 const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSSignature_1Recover(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CBLSSignature *arg1 = (CBLSSignature *) 0 ;
  std::vector< CBLSSignature > *arg2 = 0 ;
  std::vector< CBLSId > *arg3 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSSignature **)&jarg1; 
  arg2 = *(std::vector< CBLSSignature > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSSignature > const & reference is null");
    return 0;
  } 
  arg3 = *(std::vector< CBLSId > **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< CBLSId > const & reference is null");
    return 0;
  } 
  result = (bool)(arg1)->Recover((std::vector< CBLSSignature > const &)*arg2,(std::vector< CBLSId > const &)*arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_delete_1CBLSSignature(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CBLSSignature *arg1 = (CBLSSignature *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CBLSSignature **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_BLSInit(JNIEnv *jenv, jclass jcls) {
  jboolean jresult = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  result = (bool)BLSInit();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1SerSize_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  result = CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey >::SerSize;
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1IsValid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  result = (bool)((CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > const *)arg1)->IsValid();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1SetBuf(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  (arg1)->SetBuf((void const *)arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1Reset(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  (arg1)->Reset();
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1GetBuf(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  ((CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > const *)arg1)->GetBuf(arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1GetHash(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  uint256 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  result = (uint256 *) &((CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > const *)arg1)->GetHash();
  *(uint256 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1UpdateHash(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  ((CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > const *)arg1)->UpdateHash();
}


SWIGEXPORT jboolean JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1SetHexStr(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jboolean jresult = 0 ;
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  std::string *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  arg2 = *(std::string **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return 0;
  } 
  result = (bool)(arg1)->SetHexStr((std::string const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1CheckMalleable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  ((CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > const *)arg1)->CheckMalleable(arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_CBLSPrivateKey_1ToString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  result = ((CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > const *)arg1)->ToString();
  *(std::string **)&jresult = new std::string((const std::string &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dashcore_blssignatures_blssignaturesJNI_delete_1CBLSPrivateKey(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *arg1 = (CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CBLSWrapper< bls::PrivateKey,int,CBLSSecretKey > **)&jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

