/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dash_bls_DashBlsJni */

#ifndef _Included_org_dash_bls_DashBlsJni
#define _Included_org_dash_bls_DashBlsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dash_bls_DashBlsJni
 * Method:    publicKeyFingerprint
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_bls_DashBlsJniSimple_publicKeyFingerprint
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_dash_bls_DashBlsJni
 * Method:    nativePublicKeyFingerprint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dash_bls_DashBlsJniSimple_nativePublicKeyFingerprint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
