/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dash_bls_BLSPublicKey */

#ifndef _Included_org_dash_bls_BLSPublicKey
#define _Included_org_dash_bls_BLSPublicKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dash_bls_BLSPublicKey
 * Method:    FromBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_bls_BLSPublicKey_FromBytes
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
