/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class BigIntegerVec extends java.util.AbstractList<SWIGTYPE_p_bn_t> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BigIntegerVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BigIntegerVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_BigIntegerVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  BigIntegerVec(java.util.Collection<SWIGTYPE_p_bn_t> e) {
    this.reserve(e.size());
    for(SWIGTYPE_p_bn_t value: e) {
      this.push_back(value);
    }
  }

  public BigIntegerVec() {
    this(blssignaturesJNI.new_BigIntegerVec__SWIG_0(), true);
  }

  public BigIntegerVec(long n) {
    this(blssignaturesJNI.new_BigIntegerVec__SWIG_1(n), true);
  }

  public BigIntegerVec(BigIntegerVec o) {
    this(blssignaturesJNI.new_BigIntegerVec__SWIG_2(BigIntegerVec.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.BigIntegerVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.BigIntegerVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.BigIntegerVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    blssignaturesJNI.BigIntegerVec_clear(swigCPtr, this);
  }

  public void push_back(SWIGTYPE_p_bn_t x) {
    blssignaturesJNI.BigIntegerVec_push_back(swigCPtr, this, SWIGTYPE_p_bn_t.getCPtr(x));
  }

  public SWIGTYPE_p_bn_t get(int i) {
    long cPtr = blssignaturesJNI.BigIntegerVec_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bn_t(cPtr, false);
  }

  public SWIGTYPE_p_bn_t set(int i, SWIGTYPE_p_bn_t VECTOR_VALUE_IN) {
    long cPtr = blssignaturesJNI.BigIntegerVec_set(swigCPtr, this, i, SWIGTYPE_p_bn_t.getCPtr(VECTOR_VALUE_IN));
    return (cPtr == 0) ? null : new SWIGTYPE_p_bn_t(cPtr, false);
  }

  public int size() {
    return blssignaturesJNI.BigIntegerVec_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.BigIntegerVec_removeRange(swigCPtr, this, from, to);
  }

}
