/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class BLS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BLS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BLS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_BLS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String getGROUP_ORDER() {
    return blssignaturesJNI.BLS_GROUP_ORDER_get();
  }

  public static boolean Init() {
    return blssignaturesJNI.BLS_Init();
  }

  public static void AssertInitialized() {
    blssignaturesJNI.BLS_AssertInitialized();
  }

  public static void Clean() {
    blssignaturesJNI.BLS_Clean();
  }

  public static void HashPubKeys(SWIGTYPE_p_bn_t output, long numOutputs, ByteArrayVector serPubKeys, SWIGTYPE_p_std__vectorT_size_t_t sortedIndices) {
    blssignaturesJNI.BLS_HashPubKeys(SWIGTYPE_p_bn_t.getCPtr(output), numOutputs, ByteArrayVector.getCPtr(serPubKeys), serPubKeys, SWIGTYPE_p_std__vectorT_size_t_t.getCPtr(sortedIndices));
  }

  public static void CheckRelicErrors() {
    blssignaturesJNI.BLS_CheckRelicErrors();
  }

  public BLS() {
    this(blssignaturesJNI.new_BLS(), true);
  }

  public final static long MESSAGE_HASH_LEN = blssignaturesJNI.BLS_MESSAGE_HASH_LEN_get();
}
