/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class ByteArrayVector extends java.util.AbstractList<SWIGTYPE_p_unsigned_char> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ByteArrayVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ByteArrayVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_ByteArrayVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  ByteArrayVector(java.util.Collection<SWIGTYPE_p_unsigned_char> e) {
    this.reserve(e.size());
    for(SWIGTYPE_p_unsigned_char value: e) {
      this.push_back(value);
    }
  }

  public ByteArrayVector() {
    this(blssignaturesJNI.new_ByteArrayVec__SWIG_0(), true);
  }

  public ByteArrayVector(long n) {
    this(blssignaturesJNI.new_ByteArrayVec__SWIG_1(n), true);
  }

  public ByteArrayVector(ByteArrayVector o) {
    this(blssignaturesJNI.new_ByteArrayVec__SWIG_2(ByteArrayVector.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.ByteArrayVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.ByteArrayVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.ByteArrayVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    blssignaturesJNI.ByteArrayVec_clear(swigCPtr, this);
  }

  public void push_back(SWIGTYPE_p_unsigned_char x) {
    blssignaturesJNI.ByteArrayVec_push_back(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(x));
  }

  public SWIGTYPE_p_unsigned_char get(int i) {
    long cPtr = blssignaturesJNI.ByteArrayVec_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char set(int i, SWIGTYPE_p_unsigned_char VECTOR_VALUE_IN) {
    long cPtr = blssignaturesJNI.ByteArrayVec_set(swigCPtr, this, i, SWIGTYPE_p_unsigned_char.getCPtr(VECTOR_VALUE_IN));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public int size() {
    return blssignaturesJNI.ByteArrayVec_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.ByteArrayVec_removeRange(swigCPtr, this, from, to);
  }

}
