/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class ChainCode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChainCode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChainCode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_ChainCode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ChainCode FromBytes(SWIGTYPE_p_uint8_t bytes) {
    return new ChainCode(blssignaturesJNI.ChainCode_FromBytes(SWIGTYPE_p_uint8_t.getCPtr(bytes)), true);
  }

  public ChainCode(ChainCode cc) {
    this(blssignaturesJNI.new_ChainCode(ChainCode.getCPtr(cc), cc), true);
  }

  public void Serialize(SWIGTYPE_p_uint8_t buffer) {
    blssignaturesJNI.ChainCode_Serialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(buffer));
  }

  public SWIGTYPE_p_std__vectorT_uint8_t_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_uint8_t_t(blssignaturesJNI.ChainCode_Serialize__SWIG_1(swigCPtr, this), true);
  }

  public final static long CHAIN_CODE_SIZE = blssignaturesJNI.ChainCode_CHAIN_CODE_SIZE_get();
}
