/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class ExtendedPrivateKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExtendedPrivateKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtendedPrivateKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_ExtendedPrivateKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ExtendedPrivateKey FromSeed(SWIGTYPE_p_uint8_t seed, long seedLen) {
    return new ExtendedPrivateKey(blssignaturesJNI.ExtendedPrivateKey_FromSeed(SWIGTYPE_p_uint8_t.getCPtr(seed), seedLen), true);
  }

  public static ExtendedPrivateKey FromBytes(SWIGTYPE_p_uint8_t serialized) {
    return new ExtendedPrivateKey(blssignaturesJNI.ExtendedPrivateKey_FromBytes(SWIGTYPE_p_uint8_t.getCPtr(serialized)), true);
  }

  public ExtendedPrivateKey PrivateChild(SWIGTYPE_p_uint32_t i) {
    return new ExtendedPrivateKey(blssignaturesJNI.ExtendedPrivateKey_PrivateChild(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(i)), true);
  }

  public SWIGTYPE_p_ExtendedPublicKey PublicChild(SWIGTYPE_p_uint32_t i) {
    return new SWIGTYPE_p_ExtendedPublicKey(blssignaturesJNI.ExtendedPrivateKey_PublicChild(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(i)), true);
  }

  public SWIGTYPE_p_uint32_t GetVersion() {
    return new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPrivateKey_GetVersion(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint8_t GetDepth() {
    return new SWIGTYPE_p_uint8_t(blssignaturesJNI.ExtendedPrivateKey_GetDepth(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint32_t GetParentFingerprint() {
    return new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPrivateKey_GetParentFingerprint(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint32_t GetChildNumber() {
    return new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPrivateKey_GetChildNumber(swigCPtr, this), true);
  }

  public ChainCode GetChainCode() {
    return new ChainCode(blssignaturesJNI.ExtendedPrivateKey_GetChainCode(swigCPtr, this), true);
  }

  public SWIGTYPE_p_PrivateKey GetPrivateKey() {
    return new SWIGTYPE_p_PrivateKey(blssignaturesJNI.ExtendedPrivateKey_GetPrivateKey(swigCPtr, this), true);
  }

  public SWIGTYPE_p_PublicKey GetPublicKey() {
    return new SWIGTYPE_p_PublicKey(blssignaturesJNI.ExtendedPrivateKey_GetPublicKey(swigCPtr, this), true);
  }

  public SWIGTYPE_p_ExtendedPublicKey GetExtendedPublicKey() {
    return new SWIGTYPE_p_ExtendedPublicKey(blssignaturesJNI.ExtendedPrivateKey_GetExtendedPublicKey(swigCPtr, this), true);
  }

  public void Serialize(SWIGTYPE_p_uint8_t buffer) {
    blssignaturesJNI.ExtendedPrivateKey_Serialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(buffer));
  }

  public SWIGTYPE_p_std__vectorT_uint8_t_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_uint8_t_t(blssignaturesJNI.ExtendedPrivateKey_Serialize__SWIG_1(swigCPtr, this), true);
  }

  public final static SWIGTYPE_p_uint32_t EXTENDED_PRIVATE_KEY_SIZE = new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPrivateKey_EXTENDED_PRIVATE_KEY_SIZE_get(), false);
}
