/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class ExtendedPublicKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExtendedPublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtendedPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_ExtendedPublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ExtendedPublicKey FromBytes(SWIGTYPE_p_uint8_t serialized) {
    return new ExtendedPublicKey(blssignaturesJNI.ExtendedPublicKey_FromBytes(SWIGTYPE_p_uint8_t.getCPtr(serialized)), true);
  }

  public ExtendedPublicKey PublicChild(SWIGTYPE_p_uint32_t i) {
    return new ExtendedPublicKey(blssignaturesJNI.ExtendedPublicKey_PublicChild(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(i)), true);
  }

  public SWIGTYPE_p_uint32_t GetVersion() {
    return new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPublicKey_GetVersion(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint8_t GetDepth() {
    return new SWIGTYPE_p_uint8_t(blssignaturesJNI.ExtendedPublicKey_GetDepth(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint32_t GetParentFingerprint() {
    return new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPublicKey_GetParentFingerprint(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint32_t GetChildNumber() {
    return new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPublicKey_GetChildNumber(swigCPtr, this), true);
  }

  public ChainCode GetChainCode() {
    return new ChainCode(blssignaturesJNI.ExtendedPublicKey_GetChainCode(swigCPtr, this), true);
  }

  public SWIGTYPE_p_PublicKey GetPublicKey() {
    return new SWIGTYPE_p_PublicKey(blssignaturesJNI.ExtendedPublicKey_GetPublicKey(swigCPtr, this), true);
  }

  public void Serialize(SWIGTYPE_p_uint8_t buffer) {
    blssignaturesJNI.ExtendedPublicKey_Serialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(buffer));
  }

  public SWIGTYPE_p_std__vectorT_uint8_t_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_uint8_t_t(blssignaturesJNI.ExtendedPublicKey_Serialize__SWIG_1(swigCPtr, this), true);
  }

  public final static SWIGTYPE_p_uint32_t VERSION = new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPublicKey_VERSION_get(), false);
  public final static SWIGTYPE_p_uint32_t EXTENDED_PUBLIC_KEY_SIZE = new SWIGTYPE_p_uint32_t(blssignaturesJNI.ExtendedPublicKey_EXTENDED_PUBLIC_KEY_SIZE_get(), false);
}
