/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class ExtendedPublicKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExtendedPublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtendedPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_ExtendedPublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ExtendedPublicKey FromBytes(byte[] serialized) {
    return new ExtendedPublicKey(blssignaturesJNI.ExtendedPublicKey_FromBytes(serialized), true);
  }

  public ExtendedPublicKey PublicChild(long i) {
    return new ExtendedPublicKey(blssignaturesJNI.ExtendedPublicKey_PublicChild(swigCPtr, this, i), true);
  }

  public long GetVersion() {
    return blssignaturesJNI.ExtendedPublicKey_GetVersion(swigCPtr, this);
  }

  public short GetDepth() {
    return blssignaturesJNI.ExtendedPublicKey_GetDepth(swigCPtr, this);
  }

  public long GetParentFingerprint() {
    return blssignaturesJNI.ExtendedPublicKey_GetParentFingerprint(swigCPtr, this);
  }

  public long GetChildNumber() {
    return blssignaturesJNI.ExtendedPublicKey_GetChildNumber(swigCPtr, this);
  }

  public ChainCode GetChainCode() {
    return new ChainCode(blssignaturesJNI.ExtendedPublicKey_GetChainCode(swigCPtr, this), true);
  }

  public SWIGTYPE_p_PublicKey GetPublicKey() {
    return new SWIGTYPE_p_PublicKey(blssignaturesJNI.ExtendedPublicKey_GetPublicKey(swigCPtr, this), true);
  }

  public void Serialize(byte[] buffer) {
    blssignaturesJNI.ExtendedPublicKey_Serialize__SWIG_0(swigCPtr, this, buffer);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(blssignaturesJNI.ExtendedPublicKey_Serialize__SWIG_1(swigCPtr, this), true);
  }

  public final static long VERSION = blssignaturesJNI.ExtendedPublicKey_VERSION_get();
  public final static long EXTENDED_PUBLIC_KEY_SIZE = blssignaturesJNI.ExtendedPublicKey_EXTENDED_PUBLIC_KEY_SIZE_get();
}
