/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;


public class InsecureSignatureVector extends java.util.AbstractList<InsecureSignature> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InsecureSignatureVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InsecureSignatureVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_SignatureVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  InsecureSignatureVector(java.util.Collection<InsecureSignature> e) {
    this.reserve(e.size());
    for(InsecureSignature value: e) {
      this.push_back(value);
    }
  }

  public InsecureSignatureVector() {
    this(blssignaturesJNI.new_SignatureVector__SWIG_0(), true);
  }

  public InsecureSignatureVector(InsecureSignatureVector o) {
    this(blssignaturesJNI.new_SignatureVector__SWIG_2(InsecureSignatureVector.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.SignatureVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.SignatureVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.SignatureVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    blssignaturesJNI.SignatureVector_clear(swigCPtr, this);
  }

  public void push_back(InsecureSignature x) {
    blssignaturesJNI.InsecureSignatureVector_push_back(swigCPtr, this, InsecureSignature.getCPtr(x), x);
  }

  public InsecureSignature get(int i) {
    return new InsecureSignature(blssignaturesJNI.InsecureSignatureVector_get(swigCPtr, this, i), false);
  }

  public InsecureSignature set(int i, InsecureSignature VECTOR_VALUE_IN) {
    return new InsecureSignature(blssignaturesJNI.InsecureSignatureVector_set(swigCPtr, this, i, InsecureSignature.getCPtr(VECTOR_VALUE_IN), VECTOR_VALUE_IN), true);
  }

  public int size() {
    return blssignaturesJNI.SignatureVector_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.SignatureVector_removeRange(swigCPtr, this, from, to);
  }

}
