/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class PrivateKeyVec extends java.util.AbstractList<PrivateKey> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PrivateKeyVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrivateKeyVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_PrivateKeyVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  PrivateKeyVec(java.util.Collection<PrivateKey> e) {
    this.reserve(e.size());
    for(PrivateKey value: e) {
      this.push_back(value);
    }
  }

  public PrivateKeyVec() {
    this(blssignaturesJNI.new_PrivateKeyVec__SWIG_0(), true);
  }

  public PrivateKeyVec(long n) {
    this(blssignaturesJNI.new_PrivateKeyVec__SWIG_1(n), true);
  }

  public PrivateKeyVec(PrivateKeyVec o) {
    this(blssignaturesJNI.new_PrivateKeyVec__SWIG_2(PrivateKeyVec.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.PrivateKeyVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.PrivateKeyVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.PrivateKeyVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    blssignaturesJNI.PrivateKeyVec_clear(swigCPtr, this);
  }

  public void push_back(PrivateKey x) {
    blssignaturesJNI.PrivateKeyVec_push_back(swigCPtr, this, PrivateKey.getCPtr(x), x);
  }

  public PrivateKey get(int i) {
    return new PrivateKey(blssignaturesJNI.PrivateKeyVec_get(swigCPtr, this, i), false);
  }

  public PrivateKey set(int i, PrivateKey VECTOR_VALUE_IN) {
    return new PrivateKey(blssignaturesJNI.PrivateKeyVec_set(swigCPtr, this, i, PrivateKey.getCPtr(VECTOR_VALUE_IN), VECTOR_VALUE_IN), true);
  }

  public int size() {
    return blssignaturesJNI.PrivateKeyVec_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.PrivateKeyVec_removeRange(swigCPtr, this, from, to);
  }

}
