/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class PrivateKey extends BLSObject {

  protected PrivateKey(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(PrivateKey obj) {
    return (obj == null) ? 0 : obj.cPointer;
  }

  public synchronized void delete() {
        blssignaturesJNI.delete_PrivateKey(cPointer);
  }

  public static PrivateKey FromSeed(byte[] seed, long seedLen) {
    return new PrivateKey(blssignaturesJNI.PrivateKey_FromSeed(seed, seedLen), true);
  }

  public static PrivateKey FromBytes(byte[] bytes, boolean modOrder) {
    return new PrivateKey(blssignaturesJNI.PrivateKey_FromBytes__SWIG_0(bytes, modOrder), true);
  }

  public static PrivateKey FromBytes(byte[] bytes) {
    return new PrivateKey(blssignaturesJNI.PrivateKey_FromBytes__SWIG_1(bytes), true);
  }

  public PrivateKey(PrivateKey k) {
    this(blssignaturesJNI.new_PrivateKey__SWIG_0(PrivateKey.getCPtr(k), k), true);
  }

  public PublicKey GetPublicKey() {
    return new PublicKey(blssignaturesJNI.PrivateKey_GetPublicKey(cPointer, this), true);
  }

  public static PrivateKey AggregateInsecure(PrivateKeyVec privateKeys) {
    return new PrivateKey(blssignaturesJNI.PrivateKey_AggregateInsecure(PrivateKeyVec.getCPtr(privateKeys), privateKeys), true);
  }

  public static PrivateKey Aggregate(PrivateKeyVec privateKeys, SWIGTYPE_p_std__vectorT_PublicKey_t pubKeys) {
    return new PrivateKey(blssignaturesJNI.PrivateKey_Aggregate(PrivateKeyVec.getCPtr(privateKeys), privateKeys, SWIGTYPE_p_std__vectorT_PublicKey_t.getCPtr(pubKeys)), true);
  }

  public void Serialize(byte[] buffer) {
    blssignaturesJNI.PrivateKey_Serialize__SWIG_0(cPointer, this, buffer);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(blssignaturesJNI.PrivateKey_Serialize__SWIG_1(cPointer, this), true);
  }

  public InsecureSignature SignInsecure(byte[] msg, long len) {
    return new InsecureSignature(blssignaturesJNI.PrivateKey_SignInsecure(cPointer, this, msg, len), true);
  }

  public InsecureSignature SignInsecurePrehashed(byte[] hash) {
    return new InsecureSignature(blssignaturesJNI.PrivateKey_SignInsecurePrehashed(cPointer, this, hash), true);
  }

  public Signature Sign(byte[] msg, long len) {
    return new Signature(blssignaturesJNI.PrivateKey_Sign(cPointer, this, msg, len), true);
  }

  public Signature SignPrehashed(byte[] hash) {
    return new Signature(blssignaturesJNI.PrivateKey_SignPrehashed(cPointer, this, hash), true);
  }

  public final static long PRIVATE_KEY_SIZE = blssignaturesJNI.PrivateKey_PRIVATE_KEY_SIZE_get();
}
