/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class PublicKeyVector extends java.util.AbstractList<PublicKey> {
  private transient long cPointer;
  protected transient boolean owner;

  protected PublicKeyVector(long cPtr, boolean cMemoryOwn) {
    owner = cMemoryOwn;
    cPointer = cPtr;
  }

  protected static long getCPtr(PublicKeyVector obj) {
    return (obj == null) ? 0 : obj.cPointer;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (cPointer != 0) {
      if (owner) {
        owner = false;
        blssignaturesJNI.delete_PublicKeyVec(cPointer);
      }
      cPointer = 0;
    }
  }

  PublicKeyVector(java.util.Collection<PublicKey> e) {
    this.reserve(e.size());
    for(PublicKey value: e) {
      this.push_back(value);
    }
  }

  public PublicKeyVector() {
    this(blssignaturesJNI.new_PublicKeyVec__SWIG_0(), true);
  }

  public PublicKeyVector(PublicKeyVector o) {
    this(blssignaturesJNI.new_PublicKeyVec__SWIG_2(PublicKeyVector.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.PublicKeyVec_capacity(cPointer, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.PublicKeyVec_reserve(cPointer, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.PublicKeyVec_isEmpty(cPointer, this);
  }

  public void clear() {
    blssignaturesJNI.PublicKeyVec_clear(cPointer, this);
  }

  public void push_back(PublicKey x) {
    blssignaturesJNI.PublicKeyVec_push_back(cPointer, this, PublicKey.getCPtr(x), x);
  }

  public PublicKey get(int i) {
    return new PublicKey(blssignaturesJNI.PublicKeyVec_get(cPointer, this, i), false);
  }

  public PublicKey set(int i, PublicKey VECTOR_VALUE_IN) {
    return new PublicKey(blssignaturesJNI.PublicKeyVec_set(cPointer, this, i, PublicKey.getCPtr(VECTOR_VALUE_IN), VECTOR_VALUE_IN), true);
  }

  public int size() {
    return blssignaturesJNI.PublicKeyVec_size(cPointer, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.PublicKeyVec_removeRange(cPointer, this, from, to);
  }

}
