/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class PublicKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_PublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static PublicKey FromBytes(byte[] key) {
    return new PublicKey(blssignaturesJNI.PublicKey_FromBytes(key), true);
  }

  public static PublicKey FromG1(SWIGTYPE_p_g1_t key) {
    return new PublicKey(blssignaturesJNI.PublicKey_FromG1(SWIGTYPE_p_g1_t.getCPtr(key)), true);
  }

  public PublicKey(PublicKey pubKey) {
    this(blssignaturesJNI.new_PublicKey(PublicKey.getCPtr(pubKey), pubKey), true);
  }

  public static PublicKey AggregateInsecure(PublicKeyVec pubKeys) {
    return new PublicKey(blssignaturesJNI.PublicKey_AggregateInsecure(PublicKeyVec.getCPtr(pubKeys), pubKeys), true);
  }

  public static PublicKey Aggregate(PublicKeyVec pubKeys) {
    return new PublicKey(blssignaturesJNI.PublicKey_Aggregate(PublicKeyVec.getCPtr(pubKeys), pubKeys), true);
  }

  public void Serialize(byte[] buffer) {
    blssignaturesJNI.PublicKey_Serialize__SWIG_0(swigCPtr, this, buffer);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(blssignaturesJNI.PublicKey_Serialize__SWIG_1(swigCPtr, this), true);
  }

  public long GetFingerprint() {
    return blssignaturesJNI.PublicKey_GetFingerprint(swigCPtr, this);
  }

  public final static long PUBLIC_KEY_SIZE = blssignaturesJNI.PublicKey_PUBLIC_KEY_SIZE_get();
}
