/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;


public class SignatureVector extends java.util.AbstractList<Signature> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SignatureVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SignatureVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blssignaturesJNI.delete_SignatureVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  SignatureVector(java.util.Collection<Signature> e) {
    this.reserve(e.size());
    for(Signature value: e) {
      this.push_back(value);
    }
  }

  public SignatureVector() {
    this(blssignaturesJNI.new_SignatureVector__SWIG_0(), true);
  }

  public SignatureVector(SignatureVector o) {
    this(blssignaturesJNI.new_SignatureVector__SWIG_2(SignatureVector.getCPtr(o), o), true);
  }

  public long capacity() {
    return blssignaturesJNI.SignatureVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    blssignaturesJNI.SignatureVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return blssignaturesJNI.SignatureVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    blssignaturesJNI.SignatureVector_clear(swigCPtr, this);
  }

  public void push_back(Signature x) {
    blssignaturesJNI.SignatureVector_push_back(swigCPtr, this, Signature.getCPtr(x), x);
  }

  public Signature get(int i) {
    return new Signature(blssignaturesJNI.SignatureVector_get(swigCPtr, this, i), false);
  }

  public Signature set(int i, Signature VECTOR_VALUE_IN) {
    return new Signature(blssignaturesJNI.SignatureVector_set(swigCPtr, this, i, Signature.getCPtr(VECTOR_VALUE_IN), VECTOR_VALUE_IN), true);
  }

  public int size() {
    return blssignaturesJNI.SignatureVector_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    blssignaturesJNI.SignatureVector_removeRange(swigCPtr, this, from, to);
  }

}
