/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.blssignatures;

public class Signature extends BLSObject {

  protected Signature(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Signature obj) {
    return (obj == null) ? 0 : obj.cPointer;
  }

  public synchronized void delete() {
        blssignaturesJNI.delete_Signature(cPointer);
  }

  public static Signature FromBytes(SWIGTYPE_p_unsigned_char data) {
    return new Signature(blssignaturesJNI.Signature_FromBytes__SWIG_0(SWIGTYPE_p_unsigned_char.getCPtr(data)), true);
  }

  public static Signature FromBytes(SWIGTYPE_p_unsigned_char data, SWIGTYPE_p_AggregationInfo info) {
    return new Signature(blssignaturesJNI.Signature_FromBytes__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(data), SWIGTYPE_p_AggregationInfo.getCPtr(info)), true);
  }

  public static Signature FromG2(SWIGTYPE_p_g2_t element) {
    return new Signature(blssignaturesJNI.Signature_FromG2__SWIG_0(SWIGTYPE_p_g2_t.getCPtr(element)), true);
  }

  public static Signature FromG2(SWIGTYPE_p_g2_t element, SWIGTYPE_p_AggregationInfo info) {
    return new Signature(blssignaturesJNI.Signature_FromG2__SWIG_1(SWIGTYPE_p_g2_t.getCPtr(element), SWIGTYPE_p_AggregationInfo.getCPtr(info)), true);
  }

  public static Signature FromInsecureSig(InsecureSignature sig) {
    return new Signature(blssignaturesJNI.Signature_FromInsecureSig__SWIG_0(InsecureSignature.getCPtr(sig), sig), true);
  }

  public static Signature FromInsecureSig(InsecureSignature sig, AggregationInfo info) {
    return new Signature(blssignaturesJNI.Signature_FromInsecureSig__SWIG_1(InsecureSignature.getCPtr(sig), sig, AggregationInfo.getCPtr(info)), true);
  }

  public Signature(Signature signature) {
    this(blssignaturesJNI.new_Signature(Signature.getCPtr(signature), signature), true);
  }

  public boolean Verify() {
    return blssignaturesJNI.Signature_Verify(cPointer, this);
  }

  public static Signature AggregateSigs(SWIGTYPE_p_std__vectorT_bls__Signature_t sigs) {
    return new Signature(blssignaturesJNI.Signature_AggregateSigs(SWIGTYPE_p_std__vectorT_bls__Signature_t.getCPtr(sigs)), true);
  }

  public Signature DivideBy(SWIGTYPE_p_std__vectorT_bls__Signature_t divisorSigs) {
    return new Signature(blssignaturesJNI.Signature_DivideBy(cPointer, this, SWIGTYPE_p_std__vectorT_bls__Signature_t.getCPtr(divisorSigs)), true);
  }

  public AggregationInfo GetAggregationInfo() {
    long cPtr = blssignaturesJNI.Signature_GetAggregationInfo(cPointer, this);
    return (cPtr == 0) ? null : new AggregationInfo(cPtr, false);
  }

  public void SetAggregationInfo(AggregationInfo newAggregationInfo) {
    blssignaturesJNI.Signature_SetAggregationInfo(cPointer, this, AggregationInfo.getCPtr(newAggregationInfo));
  }

  public void Serialize(byte[] buffer) {
    blssignaturesJNI.Signature_Serialize__SWIG_0(cPointer, this, buffer);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(blssignaturesJNI.Signature_Serialize__SWIG_1(cPointer, this), true);
  }

  public final static long SIGNATURE_SIZE = blssignaturesJNI.Signature_SIGNATURE_SIZE_get();
}
