/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dash_blssignatures_blssignaturesJNI */

#ifndef _Included_org_dash_blssignatures_blssignaturesJNI
#define _Included_org_dash_blssignatures_blssignaturesJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BLS_GROUP_ORDER_get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BLS_1GROUP_1ORDER_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BLS_MESSAGE_HASH_LEN_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BLS_1MESSAGE_1HASH_1LEN_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BLS_Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BLS_1Init
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BLS_AssertInitialized
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BLS_1AssertInitialized
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BLS_Clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BLS_1Clean
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BLS_HashPubKeys
 * Signature: (JJJLorg/dash/blssignatures/ByteArrayVector;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BLS_1HashPubKeys
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BLS_CheckRelicErrors
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BLS_1CheckRelicErrors
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_BLS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1BLS
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_BLS
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1BLS
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ChainCode_CHAIN_CODE_SIZE_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ChainCode_1CHAIN_1CODE_1SIZE_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ChainCode_FromBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ChainCode_1FromBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_ChainCode
 * Signature: (JLorg/dash/blssignatures/ChainCode;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1ChainCode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ChainCode_Serialize__SWIG_0
 * Signature: (JLorg/dash/blssignatures/ChainCode;[B)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ChainCode_1Serialize_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ChainCode_Serialize__SWIG_1
 * Signature: (JLorg/dash/blssignatures/ChainCode;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ChainCode_1Serialize_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_ChainCode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1ChainCode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_EXTENDED_PRIVATE_KEY_SIZE_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1EXTENDED_1PRIVATE_1KEY_1SIZE_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_FromSeed
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1FromSeed
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_FromBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1FromBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_PrivateChild
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1PrivateChild
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_PublicChild
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1PublicChild
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetVersion
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetVersion
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetDepth
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)S
 */
JNIEXPORT jshort JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetDepth
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetParentFingerprint
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetParentFingerprint
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetChildNumber
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetChildNumber
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetChainCode
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetChainCode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetPrivateKey
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetPrivateKey
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetPublicKey
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetPublicKey
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_GetExtendedPublicKey
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1GetExtendedPublicKey
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_Serialize__SWIG_0
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;[B)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1Serialize_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPrivateKey_Serialize__SWIG_1
 * Signature: (JLorg/dash/blssignatures/ExtendedPrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPrivateKey_1Serialize_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_ExtendedPrivateKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1ExtendedPrivateKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_VERSION_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1VERSION_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_EXTENDED_PUBLIC_KEY_SIZE_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1EXTENDED_1PUBLIC_1KEY_1SIZE_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_FromBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1FromBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_PublicChild
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1PublicChild
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_GetVersion
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1GetVersion
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_GetDepth
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;)S
 */
JNIEXPORT jshort JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1GetDepth
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_GetParentFingerprint
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1GetParentFingerprint
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_GetChildNumber
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1GetChildNumber
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_GetChainCode
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1GetChainCode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_GetPublicKey
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1GetPublicKey
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_Serialize__SWIG_0
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;[B)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1Serialize_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ExtendedPublicKey_Serialize__SWIG_1
 * Signature: (JLorg/dash/blssignatures/ExtendedPublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ExtendedPublicKey_1Serialize_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_ExtendedPublicKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1ExtendedPublicKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_PRIVATE_KEY_SIZE_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1PRIVATE_1KEY_1SIZE_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_FromSeed
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1FromSeed
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_FromBytes__SWIG_0
 * Signature: ([BZ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1FromBytes_1_1SWIG_10
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_FromBytes__SWIG_1
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1FromBytes_1_1SWIG_11
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PrivateKey__SWIG_0
 * Signature: (JLorg/dash/blssignatures/PrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PrivateKey_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_PrivateKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1PrivateKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_GetPublicKey
 * Signature: (JLorg/dash/blssignatures/PrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1GetPublicKey
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_AggregateInsecure
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1AggregateInsecure
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_Aggregate
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1Aggregate
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_Serialize__SWIG_0
 * Signature: (JLorg/dash/blssignatures/PrivateKey;[B)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1Serialize_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_Serialize__SWIG_1
 * Signature: (JLorg/dash/blssignatures/PrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1Serialize_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_SignInsecure
 * Signature: (JLorg/dash/blssignatures/PrivateKey;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1SignInsecure
  (JNIEnv *, jclass, jlong, jobject, jbyteArray, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_SignInsecurePrehashed
 * Signature: (JLorg/dash/blssignatures/PrivateKey;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1SignInsecurePrehashed
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_Sign
 * Signature: (JLorg/dash/blssignatures/PrivateKey;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1Sign
  (JNIEnv *, jclass, jlong, jobject, jbyteArray, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKey_SignPrehashed
 * Signature: (JLorg/dash/blssignatures/PrivateKey;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKey_1SignPrehashed
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_PUBLIC_KEY_SIZE_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1PUBLIC_1KEY_1SIZE_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_FromBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1FromBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_FromG1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1FromG1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PublicKey
 * Signature: (JLorg/dash/blssignatures/PublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PublicKey
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_AggregateInsecure
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1AggregateInsecure
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_Aggregate
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1Aggregate
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_Serialize__SWIG_0
 * Signature: (JLorg/dash/blssignatures/PublicKey;[B)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1Serialize_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_Serialize__SWIG_1
 * Signature: (JLorg/dash/blssignatures/PublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1Serialize_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKey_GetFingerprint
 * Signature: (JLorg/dash/blssignatures/PublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKey_1GetFingerprint
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_PublicKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1PublicKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_SIGNATURE_SIZE_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1SIGNATURE_1SIZE_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_FromBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1FromBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_FromG2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1FromG2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_InsecureSignature
 * Signature: (JLorg/dash/blssignatures/InsecureSignature;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1InsecureSignature
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_Verify
 * Signature: (JLorg/dash/blssignatures/InsecureSignature;JJLorg/dash/blssignatures/PublicKeyVector;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1Verify
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_Aggregate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1Aggregate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_DivideBy
 * Signature: (JLorg/dash/blssignatures/InsecureSignature;J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1DivideBy
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_Serialize__SWIG_0
 * Signature: (JLorg/dash/blssignatures/InsecureSignature;[B)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1Serialize_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    InsecureSignature_Serialize__SWIG_1
 * Signature: (JLorg/dash/blssignatures/InsecureSignature;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_InsecureSignature_1Serialize_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_InsecureSignature
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1InsecureSignature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_SIGNATURE_SIZE_get
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1SIGNATURE_1SIZE_1get
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_FromBytes__SWIG_0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1FromBytes_1_1SWIG_10
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_FromBytes__SWIG_1
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1FromBytes_1_1SWIG_11
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_FromG2__SWIG_0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1FromG2_1_1SWIG_10
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_FromG2__SWIG_1
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1FromG2_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_FromInsecureSig__SWIG_0
 * Signature: (JLorg/dash/blssignatures/InsecureSignature;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1FromInsecureSig_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_FromInsecureSig__SWIG_1
 * Signature: (JLorg/dash/blssignatures/InsecureSignature;J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1FromInsecureSig_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_Signature
 * Signature: (JLorg/dash/blssignatures/Signature;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1Signature
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_Verify
 * Signature: (JLorg/dash/blssignatures/Signature;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1Verify
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_AggregateSigs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1AggregateSigs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_DivideBy
 * Signature: (JLorg/dash/blssignatures/Signature;J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1DivideBy
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_GetAggregationInfo
 * Signature: (JLorg/dash/blssignatures/Signature;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1GetAggregationInfo
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_SetAggregationInfo
 * Signature: (JLorg/dash/blssignatures/Signature;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1SetAggregationInfo
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_Serialize__SWIG_0
 * Signature: (JLorg/dash/blssignatures/Signature;[B)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1Serialize_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    Signature_Serialize__SWIG_1
 * Signature: (JLorg/dash/blssignatures/Signature;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_Signature_1Serialize_1_1SWIG_11
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_Signature
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1Signature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_FromMsgHash
 * Signature: (JLorg/dash/blssignatures/PublicKey;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1FromMsgHash
  (JNIEnv *, jclass, jlong, jobject, jbyteArray);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_FromMsg
 * Signature: (JLorg/dash/blssignatures/PublicKey;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1FromMsg
  (JNIEnv *, jclass, jlong, jobject, jbyteArray, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_FromVectors
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;JLorg/dash/blssignatures/ByteArrayVector;JLorg/dash/blssignatures/BigIntegerVec;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1FromVectors
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_MergeInfos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1MergeInfos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_AggregationInfo__SWIG_0
 * Signature: (JLorg/dash/blssignatures/AggregationInfo;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1AggregationInfo_1_1SWIG_10
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_RemoveEntries
 * Signature: (JLorg/dash/blssignatures/AggregationInfo;JLorg/dash/blssignatures/ByteArrayVector;JLorg/dash/blssignatures/PublicKeyVector;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1RemoveEntries
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_GetExponent
 * Signature: (JLorg/dash/blssignatures/AggregationInfo;J[BJLorg/dash/blssignatures/PublicKey;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1GetExponent
  (JNIEnv *, jclass, jlong, jobject, jlong, jbyteArray, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_GetPubKeys
 * Signature: (JLorg/dash/blssignatures/AggregationInfo;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1GetPubKeys
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_GetMessageHashes
 * Signature: (JLorg/dash/blssignatures/AggregationInfo;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1GetMessageHashes
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    AggregationInfo_Empty
 * Signature: (JLorg/dash/blssignatures/AggregationInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_AggregationInfo_1Empty
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_AggregationInfo__SWIG_1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1AggregationInfo_1_1SWIG_11
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_AggregationInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1AggregationInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PublicKeyVec__SWIG_0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PublicKeyVec_1_1SWIG_10
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PublicKeyVec__SWIG_1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PublicKeyVec_1_1SWIG_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PublicKeyVec__SWIG_2
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PublicKeyVec_1_1SWIG_12
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_capacity
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1capacity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_reserve
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1reserve
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_isEmpty
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1isEmpty
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_clear
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1clear
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_push_back
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;JLorg/dash/blssignatures/PublicKey;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1push_1back
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_get
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1get
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_set
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;IJLorg/dash/blssignatures/PublicKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1set
  (JNIEnv *, jclass, jlong, jobject, jint, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_size
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;)I
 */
JNIEXPORT jint JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1size
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PublicKeyVec_removeRange
 * Signature: (JLorg/dash/blssignatures/PublicKeyVector;II)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PublicKeyVec_1removeRange
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_PublicKeyVec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1PublicKeyVec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PrivateKeyVec__SWIG_0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PrivateKeyVec_1_1SWIG_10
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PrivateKeyVec__SWIG_1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PrivateKeyVec_1_1SWIG_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_PrivateKeyVec__SWIG_2
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1PrivateKeyVec_1_1SWIG_12
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_capacity
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1capacity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_reserve
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1reserve
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_isEmpty
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1isEmpty
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_clear
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1clear
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_push_back
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;JLorg/dash/blssignatures/PrivateKey;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1push_1back
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_get
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;I)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1get
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_set
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;IJLorg/dash/blssignatures/PrivateKey;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1set
  (JNIEnv *, jclass, jlong, jobject, jint, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_size
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;)I
 */
JNIEXPORT jint JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1size
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    PrivateKeyVec_removeRange
 * Signature: (JLorg/dash/blssignatures/PrivateKeyVec;II)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_PrivateKeyVec_1removeRange
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_PrivateKeyVec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1PrivateKeyVec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_ByteArrayVec__SWIG_0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1ByteArrayVec_1_1SWIG_10
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_ByteArrayVec__SWIG_1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1ByteArrayVec_1_1SWIG_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_ByteArrayVec__SWIG_2
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1ByteArrayVec_1_1SWIG_12
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_capacity
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1capacity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_reserve
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1reserve
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_isEmpty
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1isEmpty
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_clear
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1clear
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_push_back
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1push_1back
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_get
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1get
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_set
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1set
  (JNIEnv *, jclass, jlong, jobject, jint, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_size
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;)I
 */
JNIEXPORT jint JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1size
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    ByteArrayVec_removeRange
 * Signature: (JLorg/dash/blssignatures/ByteArrayVector;II)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_ByteArrayVec_1removeRange
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_ByteArrayVec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1ByteArrayVec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_BigIntegerVec__SWIG_0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1BigIntegerVec_1_1SWIG_10
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_BigIntegerVec__SWIG_1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1BigIntegerVec_1_1SWIG_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_BigIntegerVec__SWIG_2
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1BigIntegerVec_1_1SWIG_12
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_capacity
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1capacity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_reserve
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1reserve
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_isEmpty
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1isEmpty
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_clear
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1clear
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_push_back
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1push_1back
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_get
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;I)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1get
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_set
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1set
  (JNIEnv *, jclass, jlong, jobject, jint, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_size
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;)I
 */
JNIEXPORT jint JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1size
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    BigIntegerVec_removeRange
 * Signature: (JLorg/dash/blssignatures/BigIntegerVec;II)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_BigIntegerVec_1removeRange
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_BigIntegerVec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1BigIntegerVec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_SignatureVector__SWIG_0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1SignatureVector_1_1SWIG_10
  (JNIEnv *, jclass);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_SignatureVector__SWIG_1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1SignatureVector_1_1SWIG_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    new_SignatureVector__SWIG_2
 * Signature: (JLorg/dash/blssignatures/SignatureVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_new_1SignatureVector_1_1SWIG_12
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_capacity
 * Signature: (JLorg/dash/blssignatures/SignatureVector;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1capacity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_reserve
 * Signature: (JLorg/dash/blssignatures/SignatureVector;J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1reserve
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_isEmpty
 * Signature: (JLorg/dash/blssignatures/SignatureVector;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1isEmpty
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_clear
 * Signature: (JLorg/dash/blssignatures/SignatureVector;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1clear
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_push_back
 * Signature: (JLorg/dash/blssignatures/SignatureVector;JLorg/dash/blssignatures/Signature;)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1push_1back
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_get
 * Signature: (JLorg/dash/blssignatures/SignatureVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1get
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_set
 * Signature: (JLorg/dash/blssignatures/SignatureVector;IJLorg/dash/blssignatures/Signature;)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1set
  (JNIEnv *, jclass, jlong, jobject, jint, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_size
 * Signature: (JLorg/dash/blssignatures/SignatureVector;)I
 */
JNIEXPORT jint JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1size
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    SignatureVector_removeRange
 * Signature: (JLorg/dash/blssignatures/SignatureVector;II)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_SignatureVector_1removeRange
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_dash_blssignatures_blssignaturesJNI
 * Method:    delete_SignatureVector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dash_blssignatures_blssignaturesJNI_delete_1SignatureVector
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
